name: Manual deploy main branch to AWS

on: 
  workflow_dispatch:
    
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      run: |
        cd app
        mvn -B package --file pom.xml
    
    - name: rename war
      run: mv app/target/proj-1.0-SNAPSHOT.war app/target/pecheur.war
        
    - name: Set SSH keys
      run: |
        touch key.pem
        echo "${{ secrets.AMT_DMZ_KEY }}" > key.pem
        chmod 400 key.pem
        touch key2.pem
        echo "${{ secrets.AMT_KEY }}" > key2.pem
        chmod 400 key2.pem
        
    - name: SSH + Deploying
      run: |
        echo "port forwarding..."
        sudo ssh -tt -o StrictHostKeyChecking=no -fN -L 5432:${{ secrets.AMT_IP }}:22 ${{ secrets.AMT_DMZ_USERNAME }}@${{ secrets.AMT_DMZ_IP }} -i key.pem
        echo "Changing war perms..."
        sudo ssh -tt -o StrictHostKeyChecking=no -f -p 5432 -i key2.pem ${{ secrets.AMT_USERNAME }}@localhost 'sudo chmod g+w /var/lib/tomcat9/webapps/pecheur.war'
        echo "Deploying to AWS..."
        sudo scp -o StrictHostKeyChecking=no -i key2.pem -P 5432 app/target/pecheur.war ${{ secrets.AMT_USERNAME }}@localhost:/var/lib/tomcat9/webapps
