// https://github.com/marketplace/actions/semver-release
// Assuming that a PR is tagged with a "semver-compliant"
// label (patch, minor or major), then this action can create
// a tag and a GitHub release when it is merged.

name: Create release

on:
  pull_request:
    branches: main
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
